# Site settings
title: "@pearpages"
tagline: "You need systems not goals"
description: > # this means to ignore newlines until "baseurl:"
  Page and blog about programming, best practices, methodology and fun.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://pearpages.com" # the base hostname & protocol for your site

# Plugins
gems: ["jekyll-paginate"]

# Build settings
markdown: kramdown
sass:
  sass_dir: assets/sass

# Pagination
paginate: 4
paginate_path: "/blog/page:num/"

# Featured post
# The URL of the post that will be featured in the sidebar
# This is accessible as {{ page.id }} and will depend on your
# URL format settings
featured_post: /jekyll/update/2016/10/03/welcome-to-jekyll