# Site settings
title: Faction
tagline: By Pixelarity
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://example.com" # the base hostname & protocol for your site

# Plugins
gems: ["jekyll-paginate"]

# Build settings
markdown: kramdown
sass:
  sass_dir: assets/sass

# Pagination
paginate: 4
paginate_path: "/blog/page:num/"

# Featured post
# The URL of the post that will be featured in the sidebar
# This is accessible as {{ page.id }} and will depend on your
# URL format settings
featured_post: /jekyll/update/2016/10/03/welcome-to-jekyll